### PR TITLE
test: use 'edge' (unreleased) elastic-otel-python Docker image for Python auto-instrumentation

### PR DESCRIPTION
**Pull request by trentm**
/cc @xrmx
This mimics https://github.com/jackshirazi/opentelemetry/pull/1
Jack has a fork of elastic/opentelemetry that adds a very basic test of auto-instrumentation with the OTel Operator.
This is a PR to switch to using your new elastic-otel-python image for that instrumentation.

### CODE REVIEW

**Comment by trentm** [comment]
Here is a run of the test workflow (in my fork of Jack's fork, using the feature branch for this PR):
https://github.com/trentm/jackshirazi-opentelemetry/actions/runs/11036567810/job/30655299710

**Comment by trentm** [comment]
All the test suite does is start everything up, start a test Python app, set `OTEL_LOG_LEVEL=debug`, then watch the application pod's log for this string:

https://github.com/trentm/jackshirazi-opentelemetry/blob/trentm/edot-python/test/operator/python/test-app.yaml#L18-L19
```
Exception while exporting metrics HTTPConnectionPool
```

**Comment by trentm** [comment]
That test run failed, so something needs to change here.

**Comment by xrmx** [comment]
It's this one I guess:

```
ValueError: Propagator b3 not found. It is either misspelled or not installed.
```

Will add but also need to fix to not override the version of the tagged release

**Comment by trentm** [comment]
>...but also need to fix to not override the version of the tagged release

Not sure what you mean. Do you mean (eventually) not using the `:edge` image for the tests?

**Comment by xrmx** [comment]
> > ...but also need to fix to not override the version of the tagged release
> 
> Not sure what you mean. Do you mean (eventually) not using the `:edge` image for the tests?

Nothing that makes sense sorry :sweat_smile: Will add the missing propagators and I'll re-run it tomorrow.

Thanks for catching this before I was tagging a new release :)

**Comment by xrmx** [comment]
PR for adding all the propagators here https://github.com/elastic/elastic-otel-python/pull/137

**Comment by trentm** [comment]
That's in and there is a new elastic-otel-python:edge image now. Re-running the test: https://github.com/trentm/jackshirazi-opentelemetry/actions/runs/11040934431

**Review by xrmx — APPROVED** [review]
LGTM. thanks!

**Comment by trentm** [comment]
@jackshirazi Please merge this one as well. Thanks.

**Review by jackshirazi — APPROVED** [review]

**Pull request merged**
